estudio/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web_estudio.urls')),
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_estudio/urls.py
from django.urls import path

from . import views

app_name = 'web_estudio'

urlpatterns = [
    path('', views.index, name='index'),
    path('turnos',views.turnos, name='turnos'),
    path('civilycomercial',views.civil_comercial, name='civilycomercial'),
    path('laboral', views.laboral, name='laboral')
]

web_estudio/models.py
from django.db import models

from django.contrib.auth.models import User

class Turno(models.Model):  
    fecha = models.DateTimeField(auto_now_add=False)
    hora = models.TimeField(auto_now_add=False)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

web_estudio/views.py
from django.shortcuts import render

from .models import Turno

def index(request):
    return render(request, 'turnos/index.html')
    

def turnos(request):
    return render(request, 'turnos/turnos.html')


def civil_comercial(request):
    return render(request, 'turnos/civilcomercial.html')

def laboral(request):
    return render(request, 'turnos/laboral.html')    

templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

    {% block title %}
        <title>titulo</title>
    {% endblock title %}
  

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  
  <!-- Custom styles for this template -->
  <link href="{% static 'css/estudio.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'web_estudio:index' %}"><span><img src="{% static 'img/logo2.png' %}" height="100" width="100"></span></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link text-warning font-weight-bold" href="#">Principal</span></a>
            </li>

            <li class="nav-item dropdown ">
                <a class="nav-link dropdown-toggle text-warning font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Servicios
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item text-dark font-weight-bold" href="{% url 'web_estudio:civilycomercial' %}">Civil y comercial</a>
                <a class="dropdown-item text-dark font-weight-bold" href="{% url 'web_estudio:laboral' %}">Laboral</a>
                <a class="dropdown-item text-dark font-weight-bold" href="#">Previsional</a>
                <a class="dropdown-item text-dark font-weight-bold" href="#">Familia</a>
                <a class="dropdown-item text-dark font-weight-bold" href="#">Sucesiones</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning font-weight-bold fas fa-phone-alt">2212222222</a>
            </li>
            <li class="nav-item">
                <a class="nav-link fab fa-facebook-square fa-2x" href="https://www.facebook.com/Ferrari-Mundet-391058734813850"  >
                  {% comment %} <span class=""></span> {% endcomment %}
                </a>
            </li>
            

            </ul>
            {% comment %} <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
            <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Buscar</button>
            </form> {% endcomment %}
     
    </div>
  </nav>
{% block header %}
  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Abogado y bufete de abogados</h1>
        <h2 class="masthead-subheading mb-0">Estudio jurídico Ferrari-Mundet</h2>
        <a href="#" class="btn btn-outline-warning btn-xl rounded-pill mt-5">Nosotros</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock header %}
  
{% block content %}
  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/firma.jpg'  %}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Quiénes Somos</h2>
            <p>Somos un Estudio Jurìdico, ubicado en La Plata centro, especializado en el derecho laboral, civil y de familia. Nos respaldan màs de 15 años de trayectoria.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/balanza.png' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-5">
            <h2 class="display-4">TITULO 1</h2>
            <p>CUALQUIER TEXTO</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/Trato.png' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">TITULO 2</h2>
            <p>CUALQUIER TEXTO</p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}


  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; FerrariMundet 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
    

    <script src="https://kit.fontawesome.com/82f0ea754b.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    {% block ExtraJS %}

    {% endblock ExtraJS %}

</body>

</html>

web_estudio/templates/turnos/civilcomercial.html
{% extends 'base1.html' %}

{% load static %}

{% block header %}
  <header class="civ text-center text-white">
    <div class="">
      <div class="container">
        <h1 class="mb-0">Derecho civil y comercial</h1>
        <h2 class="ng mb-0">Estudio jurídico Ferrari-Mundet</h2>
        
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock header %}

{% block content %}


 <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/firma.jpg' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Civil Y Comercial</h2>
            <p>Información principal relacionada a Civil y Comercial</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/balanza.png' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-5">
            <h2 class="display-4">Opcional informacion CYC</h2>
            <p>Info secundaria CYC</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/Trato.png' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Opcional 2</h2>
            <p>Informacion  secundaria CYC</p>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock content %}

web_estudio/templates/turnos/familia.html
{% extends 'base1.html' %}

{% load static %}

{% block header %}
  <header class="civ text-center text-white">
    <div class="">
      <div class="container">
        <h1 class="mb-0">Abogado y bufete de abogados</h1>
        <h2 class="ng mb-0">Estudio jurídico Ferrari-Mundet</h2>
        
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock header %}

{% block content %}
Pagina de civil y comercial
{% endblock content %}

web_estudio/templates/turnos/index.html
{% extends 'base1.html' %}
{% load static %}


{% block content %}

 <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/firma.jpg' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Quiénes Somos</h2>
            <p>Somos un Estudio Jurìdico, ubicado en La Plata centro, especializado en el derecho laboral, civil y de familia. Nos respaldan màs de 15 años de trayectoria.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/balanza.png' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-5">
            <h2 >Preguntas Frecuentes en caso de Accidente de Trabajo o Enfermedad Profesional</h2>
            <p>
¿Que  hago ante esta situación?
El empleador debe realizar la correspondiente denuncia ante la ART, con el fin de que esta  brinde rápidamente las prestaciones médicas necesarias.
</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'img/Trato.png' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">TITULO 2</h2>
            <p>¿Qué pasa si el empleador no hace la Denuncia del Accidente o Enfermedad Profesional?
En ese caso la denuncia la puede hacer el propio trabajador.
Cualquier duda o consulta podes comunicarte con nosotros y te asesoramos en todas las dudas que se te pueden presentar.</p>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock content %}

web_estudio/templates/turnos/laboral.html
{% extends 'base1.html' %}

{% load static %}

{% block header %}
  <header class="lab text-center text-white">
    <div class="">
      <div class="container">
        <h1 class="mb-0">Asesoramiento Laboral</h1>
        <h2 class="ng mb-0">Estudio jurídico Ferrari-Mundet</h2>
        
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock header %}

web_estudio/templates/turnos/previsional.html
{% extends 'base1.html' %}

{% load static %}

{% block header %}
  <header class="civ text-center text-white">
    <div class="">
      <div class="container">
        <h1 class="mb-0">Abogado y bufete de abogados</h1>
        <h2 class="ng mb-0">Estudio jurídico Ferrari-Mundet</h2>
        
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock header %}

{% block content %}
Pagina de civil y comercial
{% endblock content %}

web_estudio/templates/turnos/sucesiones.html
{% extends 'base1.html' %}

{% load static %}

{% block header %}
  <header class="civ text-center text-white">
    <div class="">
      <div class="container">
        <h1 class="mb-0">Abogado y bufete de abogados</h1>
        <h2 class="ng mb-0">Estudio jurídico Ferrari-Mundet</h2>
        
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock header %}

{% block content %}
Pagina de civil y comercial
{% endblock content %}

web_estudio/templates/turnos/turnos.html
{% include 'base.html' %}

{% block content %}

<h1>Pagina de turnos online</h1>

{% endblock content %}